tags = [
    "ai",
    "airflow",
    "api",
    "aws",
    "bayes",
    "blogs",
    "bokeh",
    "captcha",
    "css",
    "d3.js",
    "dash",
    "data",
    "data engineering",
    "data journalism",
    "data science",
    "database",
    "dataviz",
    "ddj",
    "deep learning",
    "design",
    "devops",
    "django",
    "docker",
    "elasticsearch",
    "flask",
    "geo",
    "gis",
    "git",
    "government",
    "javascript",
    "jupyter",
    "linux",
    "machine learning",
    "mongodb",
    "multilabel",
    "nlp",
    "numpy",
    "open data",
    "pandas",
    "python",
    "r",
    "scala",
    "scraping",
    "sklearn",
    "spark",
    "sql",
    "statistics",
    "tensorflow",
    "vscode",
    "web",
    "web scraping",
]
